events {
    worker_connections 1024;
}

http {
    server {
        listen 80;
        server_name localhost;
        
        location /photos/ {
            alias /usr/share/nginx/photos/;
        }

        location /audios/ {
            alias /usr/share/nginx/audios/;
        }
        location /files/ {
            alias /usr/share/nginx/files/;
        }
    }
}